### PR TITLE
Add support for initial_values for hardware interfaces when starting simulation.

### PR DESCRIPTION
**Pull request by destogl**
This PR adds support for initial values to set the hardware's initial states in the simulation.

This functionality is based on the following ros2_control PR:
- ros-controls/ros2_control#593

Here is an example of its use in FakeHardware.
- ros-controls/ros2_control#598

The ros2_control changes are released but not yet synced.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
DCO ?

**Comment by ahcorde** [comment]
Hi @destogl, I'm trying to compile this. Is `initial_values` feature only available in rolling ?

**Comment by destogl** [comment]
> Hi @destogl, I'm trying to compile this. Is `initial_values` feature only available in rolling ?

Yes, this is rolling-only feature. I am not sure if it is synced already, but it is released.

**Comment by destogl** [comment]
> DCO ?

Sorry about that!

**Comment by destogl** [comment]
> Can you add the same example as you included in this PR here ?

Do you want to have two additional files for it? In this PR I embedded the example of `initial_value` into the existing one because we actually change only one line compared to the usual examples. TBH I rather prefer approach I done here. Otherwise we just add "file-noise" without much value in them.

If you insist to add an additional example, I'll add it, but as I said, I think it is overkill.

**Review by bmagyar — APPROVED** [review]

**Comment by destogl** [comment]
@ahcorde I think we can go on with this in the same way as had to be done for `gazebo_ros2_control`.

**Comment by ahcorde** [comment]
@destogl the PR is ready https://github.com/ignitionrobotics/ign_ros2_control/pull/30

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
